### ISSUE TITLE
Undefined Ring

### ISSUE THREAD

**Issue by Shotgunface** [YukariMindGap/Necronica_Redux#3]
On the requiem doll in the experimental branch the starting ring item got updated to more than just a generic ring for example: platinum_ring or wedding_ring, just needs a specific type to be defined.  I'm not sure on the exact build that it changed, but here is my simple fix for I'm not sure which type of ring it should be . Works for build #9473
I'll try and find the exact build that broke it.
Line 37 in the nec_professions.json.
`"items": [ "dress_shirt", "boots", "leather_pouch", "ring" ],`
Fix Example:
"items": [ "dress_shirt", "boots", "leather_pouch", "platinum_ring" ],
 List of new rings:
	diamond_ring
	copper_ring
	gold_ring
	platinum_ring
	ring_engagement
	ring_purity
	ring_signet
	silver_ring
	wedding_ring

Here is the error during world load up:

 DEBUG    : item id ring is unknown
 
 FUNCTION : virtual void Single_item_creator::check_consistency() const
 FILE     : src/item_group.cpp
 LINE     : 121

When you highlight Requiem Doll:

 DEBUG    : Missing item definition: ring
 
 FUNCTION : const itype* Item_factory::find_template(const itype_id&) const
 FILE     : src/item_factory.cpp
 LINE     : 1212
Picture attached of the undefined-rings in profession list.
![nec_ring_issue](https://user-images.githubusercontent.com/25081828/62841129-90043800-bc72-11e9-9418-f7404ad1dda5.PNG)

**Comment by YukariMindGap** [comment]
Fixed in #2
