### ISSUE TITLE
Build [9995] of CDDA broke the mod!

### ISSUE THREAD

**Issue by Helldrone** [YukariMindGap/Necronica_Redux#4]
Hello! when i updated from.
![image](https://user-images.githubusercontent.com/49344129/70743978-1f088600-1d21-11ea-974a-d3eb96d2667a.png)
to
![image](https://user-images.githubusercontent.com/49344129/70744003-292a8480-1d21-11ea-8d7c-db7e10b106d8.png)

Even after trying to update the mod it keeps bonkering my save.
![image](https://user-images.githubusercontent.com/49344129/70744038-3cd5eb00-1d21-11ea-9175-c9a0adad03f7.png)

Hope anything can be done.

**Comment by Shotgunface** [comment]
I believe it's safe to close this thread as I have tried to reproduce your issues only using Dark day ahead and this mod without success. 😃

**Comment by YukariMindGap** [comment]
Latest commit should fix the issue
